### ISSUE TITLE
Packaged runners incorrectly named

### ISSUE THREAD

**Issue by thegecko** [c9/c9.ide.run#7]
If a runner is included in a package, it ends up being registered as it's filename (e.g. my-runner.run) instead of the caption specified in the runner.

This will work the first time the build is run (although it appears with '.run' at the end), but if the workspace is refreshed, the output panel can no longer find the correct runner and consequent runs will fail unless the output window is closed first.

**Comment by thegecko** [comment]
The PR referenced above ensures runners are loaded with the correct names and found when searched for. Even when these PRs are merged, however there is still an issue here in that the user plugins (and hence the runners) are loaded _after_ the run output has been loaded meaning the runner currently selected is never found.

I recommend the loading system is changed to load plugins before the panels/panes are rendered.

**Comment by nightwing** [comment]
@thegecko i have merged https://github.com/c9/core/pull/142, but on second thought i am not entirely sure if it was a good idea or not. Allowing runners to set their names independent of filename, will make it harder to find where the runner comes from. Why do you need a runner with different caption and filename?

> I recommend the loading system is changed to load plugins before the panels/panes are rendered.

Loading plugins before drawing panels is possible for core plugins that are preinstalled for a workspace type, but other plugins need to be able to load/unload without reloading whole ide.

**Comment by thegecko** [comment]
I assumed the caption in the runner was the supported way of naming the runner. If it is an internal mechanism, then I'm happy to use the name of the file as the runner name, albeit without the '.run' extension from the file name visible.

If third party plugins (specifically the runners in those plugins) cannot be loaded before the build output panel, the panel would need to be aware that the runner it needs may not be loaded when it renders after a reload and recover from this situation in another way.
